spring:
  application:
    name: flight-eureka-server 
  profiles: default

server:
  port: 7100

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    com.gokoders.server: DEBUG
  file:  /tmp/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

#  cloud:
#    config:
#      uri: http://localhost:9090